name = getArgument;
if (name=="") exit ("No argument!");
setBatchMode(true);
open(name);
run("Split Channels");
close();
run("Nrrd ... ", "nrrd=" + replace(name, ".h5j", ".nrrd"));
close();
close();
run("Quit");
